options:
    port:
        type: int
        default: 8047
        description: The port on which the service will be listening for WebSocket connections.
    log-level:
        type: string
        default: info
        description: The log level to apply to jujushell itself.
