#!/usr/bin/env python3

# Load modules from $JUJU_CHARM_DIR/lib.
import sys
sys.path.append('lib')

# Activate the virtualenv.
from charms.layer.basic import activate_venv  # noqa: E402
activate_venv()

# Start the script as usual.
from firestealer import (
    add_metrics,
    retrieve_metrics,
)  # noqa: E402
import yaml  # noqa: E402

from charms.layer import jujushell  # noqa: E402


def main():
    """Collect and add metrics to juju."""
    # Note that, for reasons, the charmhelpers config object is not available
    # in this hook.
    with open('files/config.yaml') as f:
        config = yaml.safe_load(f)
    with open('metrics.yaml') as f:
        metrics = yaml.safe_load(f)
    url = jujushell.service_url(config)
    samples = retrieve_metrics(url, metrics, noverify=True)
    add_metrics(samples)


if __name__ == '__main__':
    main()
