#!/usr/bin/env python3

# Copyright 2018 Canonical Ltd.
# Licensed under the AGPLv3, see LICENCE file for details.

# Load modules from $JUJU_CHARM_DIR/lib.
import sys
sys.path.append('lib')

# Activate the virtualenv.
from charms.layer.basic import activate_venv  # noqa: E402
activate_venv()

from charmhelpers.core import hookenv  # noqa: E402
from charms.layer import jujushell  # noqa: E402


if __name__ == '__main__':
    removed = jujushell.exterminate_containers(
        name=hookenv.action_get('name'),
        only_stopped=hookenv.action_get('only-stopped'),
        dry=hookenv.action_get('dry'))
    hookenv.action_set({'removed': ', '.join(removed)})
