#!/usr/bin/env python3

# Copyright 2017 Canonical Ltd.
# Licensed under the AGPLv3, see LICENCE file for details.

import os
import sys


# jujushell can only be imported after the layer directory has been added to
# the python path.
_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
_layer = os.path.join(_root, 'lib', 'charms', 'layer')
sys.path.insert(0, _layer)
import jujushell  # noqa: E402


if __name__ == '__main__':
    jujushell.exterminate_containers()
